### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by TonyStark** [abyzthomas/watch-folder#1]
In Manjaro Linux
`./watch-folder "/home/test/Downloads/config"`
Output is
`Scheduled for  2021-08-17 09:28:58.998779426 +0530 IST m=+30.000486798`
but in config folder several file copied and changes but no response in terminal

**Comment by abyzthomas** [comment]
Did you use the binary or compiled the source?  It seems working on RHEL, CentOS, openSUSE, etc.  Have not tried on Manjaro

**Comment by TonyStark** [comment]
binary

**Comment by abyzthomas** [comment]
![Screenshot_20210818_103841](https://user-images.githubusercontent.com/1753808/129928854-af10a0cd-5c2c-4d2e-b17d-823aca972ba3.png)

As you can see, I copied 2 files and deleted both.  all 4 events was found by the script.  It may take a few seconds to update the screen,

**Comment by TonyStark** [comment]
okay i tried again, and found that it gives me output lately
is that possible to work in realtime?
i tried `echo "12313" > test.txt`
and this event log after 5-6 second in terminal

**Comment by abyzthomas** [comment]
If you are touching the files from the same host, you can use iNotify features of Linux.  It works on filesystem events.  It will work realtime.  It will not see if you are copying a file for instance a NFS/Samba mount.

https://www.man7.org/linux/man-pages/man1/inotifywait.1.html is the documentation for inotifywait

This solution will work even if it is a shared mount.  It is not realtime.  It is polling on a schedule, I believe the binary polls every 30 seconds.  You can clone the repo and update the interval as you please, but too short will create problems.  Even, 30 seconds is too quick for large folders.

**Comment by abyzthomas** [comment]
https://www.man7.org/linux/man-pages/man1/inotifywait.1.html is the documentation for inotifywait

**Comment by TonyStark** [comment]
Thanks 
anyway i found this for my needs >> https://github.com/triole/eagle-eye/
